### ISSUE TITLE
clean up platform specific cmake for nersc machines

### ISSUE THREAD

**Issue by bandre-ucar** [BeTR-biogeochemistry-modeling/sbetr#11]
* Remove hopper.

* remove resetting compilers to env vars. Only set the compilers if you want to force a specific compiler and stop using command line options like `make CC=icc ...`

* remove commented out silo/hdf5 stuff. It's confusing and unnecessary for what betr is doing with i/o.

**Comment by bandre-ucar** [comment]
I don't have access to nersc. I'm reluctant to make these changes without the ability to test.

**Comment by jinyun1tang** [comment]
Will test this afternoon
