### ISSUE TITLE
no direct output screen or log files from within the betr library

### ISSUE THREAD

**Issue by bandre-ucar** [BeTR-biogeochemistry-modeling/sbetr#15]
Betr will be called from code that uses thread and mpi parallelism. Betr can not do any screen or file i/o in this use case. Initially, provide a flag that disables all output. Eventually, betr should provide a threadsafe logging buffer that will collect output and hand it back to the driver for safe efficient output.

**Comment by jinyun1tang** [comment]
Does this include error message? If so, I think it needs a machinery to jump out of nested function call, so that CLM or ALM can catch the error message.

**Comment by bandre-ucar** [comment]
Eventually, yes, betr library shouldn't be writing error messages or calling abort. The betr library should have a logging utility that passes messages back to the driver, and all betr interface functions should include a status flag to indicate if there is an error. The driver can then decide how to abort the run.

**Comment by jinyun1tang** [comment]
Then the only way I would see to overcome the nested error aborting issue is create an error function in betr, and that function will interact with abort function in clm or alm. So should I put such a function in driver folder?

**Comment by bandre-ucar** [comment]
My recommendation is have a betr_status struct passed through the interface:
```Fortran
type betr_status_type
    integer :: error
    char(len=betr_string_length) :: message(:)
    ! other useful info?
end type betr_status_type

subroutine BeTR_Init(betr_status, ....)
   type(betr_status_type), intent(out) :: betr_status
    ....
end subroutine
```
If an error occurs in betr, you should set the error and message appropriately.

Every function in the betr interface should include a betr_status arg. After every call to betr, the driver should check the error status.

**Comment by jinyun1tang** [comment]
So does this mean even in internal functions of betr, we'd check this error status. For instance, in the following, do we need check error message after call betr_sub2 etc., If the error is triggered in betr_sub5, this would mean jump out of betr_sub3,  and then jump out of betr_sub1, which is in betr_driver, and then return the error to clm or alm. So it become too tedious eventually with a serious of internal calls that would trigger error. I'd say create a function that can support direct abort from betr_sub6 or any of the place in betr and return back into alm or clm would be more efficient.


call betr_sub1

subroutine betr_sub1

call betr_sub2
call betr_sub3
call betr_sub4
end subroutine betr_sub1

subroutine betr_sub3

call betr_sub5
call betr_sub6
end subroutine betr_sub3

**Comment by bandre-ucar** [comment]
Some HPC machines don't respond nicely, e.g. hang or die without an error message, if one thread or one mpi process dies incorrectly. That leads to unhappy users because of wasted resources when a massive fully coupled run hangs for hours or leads to tedious debugging. The problem is that the betr library maybe called from deep inside threaded and/or mpi regions. It doesn't know what the details are though, so it can't know how to exit properly. 

What you want is to throw an exception deep in the code, catch it at the interface and had it back to the driver to exit. Fortran doesn't support that. Welcome to scientific programing in 2016 with modern fortran. The simplest, most robust solution is to fall back to old school procedural error handling. Yes, it's tedious. You might be able to get something like your call error function running correctly, but it's a lot more work than you think to get it working robustly in a thread safe way.

**Comment by jinyun1tang** [comment]
OK. So I will add an error_type and pass it as an argument, and put a check_err function after every call of a subroutine that would potentially an error message. This should be able to achieve what you suggested.

**Comment by jinyun1tang** [comment]
This is done
