### ISSUE TITLE
Cell Ids in regression output

### ISSUE THREAD

**Issue by bishtgautam** [BeTR-biogeochemistry-modeling/sbetr#18]
@bandre-ucar : Should the `do cell = 1, num_cells, cell_increment ` in [betr_regression_mod.F90#L217](https://github.com/BeTR-biogeochemistry-modeling/sbetr/blob/master/src/betr/betr_util/betr_regression_mod.F90#L217) be changed to `do cell = 1, size(data), cell_increment`?

**Comment by bandre-ucar** [comment]
I don't think so.... It's initialized inside that if block at [line 209](https://github.com/BeTR-biogeochemistry-modeling/sbetr/blob/master/src/betr/betr_util/betr_regression_mod.F90#L209) then updated at [line 212](https://github.com/BeTR-biogeochemistry-modeling/sbetr/blob/master/src/betr/betr_util/betr_regression_mod.F90#L212) if the number of expected cells exceeds the actual data size.

That could simplified to `num_cells = min(this%num_cells, size(data))` which I think is what we want....

But I could be wrong. Are you experiencing problems or do you have an example where this doesn't work?

**Comment by bishtgautam** [comment]
If `size(data) = 100` and `num_cells=5`, then `cell_increment = 20`. The do-loop becomes `do = 1, 5, 20` and value for only a single cell is written out in the regression file.

**Comment by bandre-ucar** [comment]
Ah, yep. You're correct.
