### ISSUE TITLE
need pure reaction regression test

### ISSUE THREAD

**Issue by bandre-ucar** [BeTR-biogeochemistry-modeling/sbetr#7]
The current mock-reaction test does not contain any reactions, so the solution is zero everywhere. We should add a pure reaction test with first order reactions. It can either be part of the 'mock' problem or a separate problem.

**Comment by jinyun1tang** [comment]
Will a single tracer linear decay be sufficient?

**Comment by bandre-ucar** [comment]
That would be great.

**Comment by jinyun1tang** [comment]
This is finished.
